/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const StaffPermissions = IDL.Record({
  'hasFullControl' : IDL.Bool,
  'canAccessSettings' : IDL.Bool,
  'canAccessAppointments' : IDL.Bool,
  'canAccessPatients' : IDL.Bool,
  'canAccessLeads' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminConfig = IDL.Record({
  'hashedSecurityAnswer' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'securityQuestion' : IDL.Text,
  'hashedPassword' : IDL.Opt(IDL.Vec(IDL.Nat8)),
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'appointmentTime' : IDL.Nat,
  'notes' : IDL.Text,
  'patientName' : IDL.Text,
  'mobile' : IDL.Text,
  'isFollowUp' : IDL.Bool,
});
export const Attendance = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'clinicName' : IDL.Text,
});
export const Lead = IDL.Record({
  'doctorRemark' : IDL.Text,
  'leadName' : IDL.Text,
  'addToAppointment' : IDL.Bool,
  'area' : IDL.Text,
  'treatmentWanted' : IDL.Text,
  'leadStatus' : IDL.Text,
  'rating' : IDL.Nat8,
  'mobile' : IDL.Text,
  'expectedTreatmentDate' : IDL.Int,
  'followUpDate' : IDL.Int,
});
export const Prescription = IDL.Record({
  'doctorNotes' : IDL.Text,
  'prescriptionData' : IDL.Variant({
    'typed' : IDL.Text,
    'freehand' : ExternalBlob,
    'camera' : ExternalBlob,
  }),
  'followUp' : IDL.Opt(IDL.Text),
  'prescriptionType' : IDL.Variant({
    'typed' : IDL.Null,
    'freehand' : IDL.Null,
    'camera' : IDL.Null,
  }),
  'medicalHistory' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'patientName' : IDL.Text,
  'symptoms' : IDL.Opt(IDL.Text),
  'mobile' : IDL.Text,
  'clinicName' : IDL.Text,
  'allergies' : IDL.Opt(IDL.Text),
  'appointmentId' : IDL.Opt(IDL.Nat),
  'consultationType' : IDL.Variant({
    'telemedicine' : IDL.Null,
    'inPerson' : IDL.Null,
  }),
});
export const PatientView = IDL.Record({
  'area' : IDL.Text,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'prescriptionHistory' : IDL.Vec(Prescription),
  'image' : IDL.Opt(ExternalBlob),
  'mobile' : IDL.Text,
});
export const Time = IDL.Int;
export const Staff = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addLead' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Int,
        IDL.Nat8,
        IDL.Text,
        IDL.Bool,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'addPatient' : IDL.Func(
      [IDL.Opt(ExternalBlob), IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addStaff' : IDL.Func([IDL.Text, IDL.Text, StaffPermissions], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAttendance' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'deleteAppointment' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'deleteLead' : IDL.Func([IDL.Text], [IDL.Text], []),
  'deletePatient' : IDL.Func([IDL.Text], [IDL.Text], []),
  'deletePrescription' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Text], []),
  'deleteStaff' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAdminConfig' : IDL.Func([], [IDL.Opt(AdminConfig)], ['query']),
  'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAttendance' : IDL.Func([], [IDL.Vec(Attendance)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getPatients' : IDL.Func([], [IDL.Vec(PatientView)], ['query']),
  'getPrescriptionById' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Opt(Prescription)],
      ['query'],
    ),
  'getPrescriptions' : IDL.Func([IDL.Text], [IDL.Vec(Prescription)], ['query']),
  'getPrescriptionsLastModified' : IDL.Func([], [IDL.Opt(Time)], ['query']),
  'getStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
  'getStaffPermissions' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(StaffPermissions)],
      ['query'],
    ),
  'getTodaysAppointmentsSorted' : IDL.Func(
      [],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getTomorrowAppointmentsSorted' : IDL.Func(
      [],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getUpcomingAppointmentsSorted' : IDL.Func(
      [],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [IDL.Text], []),
  'register' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [IDL.Text], []),
  'resetAdminPassword' : IDL.Func(
      [IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat8)],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePrescription' : IDL.Func([Prescription], [IDL.Text], []),
  'setAdminPassword' : IDL.Func(
      [IDL.Vec(IDL.Nat8), IDL.Text, IDL.Vec(IDL.Nat8)],
      [IDL.Text],
      [],
    ),
  'toggleFollowUpAppointment' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'unlockAdmin' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Bool], []),
  'updateAppointment' : IDL.Func([IDL.Nat, Appointment], [IDL.Text], []),
  'updateAttendance' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateLead' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Int,
        IDL.Nat8,
        IDL.Text,
        IDL.Bool,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'updatePatient' : IDL.Func(
      [IDL.Text, IDL.Opt(ExternalBlob), IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'updateStaffPermissions' : IDL.Func(
      [IDL.Text, StaffPermissions],
      [IDL.Text],
      [],
    ),
  'verifyAdminPassword' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const StaffPermissions = IDL.Record({
    'hasFullControl' : IDL.Bool,
    'canAccessSettings' : IDL.Bool,
    'canAccessAppointments' : IDL.Bool,
    'canAccessPatients' : IDL.Bool,
    'canAccessLeads' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminConfig = IDL.Record({
    'hashedSecurityAnswer' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'securityQuestion' : IDL.Text,
    'hashedPassword' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'appointmentTime' : IDL.Nat,
    'notes' : IDL.Text,
    'patientName' : IDL.Text,
    'mobile' : IDL.Text,
    'isFollowUp' : IDL.Bool,
  });
  const Attendance = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'clinicName' : IDL.Text,
  });
  const Lead = IDL.Record({
    'doctorRemark' : IDL.Text,
    'leadName' : IDL.Text,
    'addToAppointment' : IDL.Bool,
    'area' : IDL.Text,
    'treatmentWanted' : IDL.Text,
    'leadStatus' : IDL.Text,
    'rating' : IDL.Nat8,
    'mobile' : IDL.Text,
    'expectedTreatmentDate' : IDL.Int,
    'followUpDate' : IDL.Int,
  });
  const Prescription = IDL.Record({
    'doctorNotes' : IDL.Text,
    'prescriptionData' : IDL.Variant({
      'typed' : IDL.Text,
      'freehand' : ExternalBlob,
      'camera' : ExternalBlob,
    }),
    'followUp' : IDL.Opt(IDL.Text),
    'prescriptionType' : IDL.Variant({
      'typed' : IDL.Null,
      'freehand' : IDL.Null,
      'camera' : IDL.Null,
    }),
    'medicalHistory' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'patientName' : IDL.Text,
    'symptoms' : IDL.Opt(IDL.Text),
    'mobile' : IDL.Text,
    'clinicName' : IDL.Text,
    'allergies' : IDL.Opt(IDL.Text),
    'appointmentId' : IDL.Opt(IDL.Nat),
    'consultationType' : IDL.Variant({
      'telemedicine' : IDL.Null,
      'inPerson' : IDL.Null,
    }),
  });
  const PatientView = IDL.Record({
    'area' : IDL.Text,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'prescriptionHistory' : IDL.Vec(Prescription),
    'image' : IDL.Opt(ExternalBlob),
    'mobile' : IDL.Text,
  });
  const Time = IDL.Int;
  const Staff = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addLead' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Int,
          IDL.Nat8,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'addPatient' : IDL.Func(
        [IDL.Opt(ExternalBlob), IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addStaff' : IDL.Func(
        [IDL.Text, IDL.Text, StaffPermissions],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAttendance' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'deleteAppointment' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'deleteLead' : IDL.Func([IDL.Text], [IDL.Text], []),
    'deletePatient' : IDL.Func([IDL.Text], [IDL.Text], []),
    'deletePrescription' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Text], []),
    'deleteStaff' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAdminConfig' : IDL.Func([], [IDL.Opt(AdminConfig)], ['query']),
    'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAttendance' : IDL.Func([], [IDL.Vec(Attendance)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getPatients' : IDL.Func([], [IDL.Vec(PatientView)], ['query']),
    'getPrescriptionById' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(Prescription)],
        ['query'],
      ),
    'getPrescriptions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Prescription)],
        ['query'],
      ),
    'getPrescriptionsLastModified' : IDL.Func([], [IDL.Opt(Time)], ['query']),
    'getStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
    'getStaffPermissions' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(StaffPermissions)],
        ['query'],
      ),
    'getTodaysAppointmentsSorted' : IDL.Func(
        [],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getTomorrowAppointmentsSorted' : IDL.Func(
        [],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getUpcomingAppointmentsSorted' : IDL.Func(
        [],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [IDL.Text], []),
    'register' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [IDL.Text], []),
    'resetAdminPassword' : IDL.Func(
        [IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat8)],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePrescription' : IDL.Func([Prescription], [IDL.Text], []),
    'setAdminPassword' : IDL.Func(
        [IDL.Vec(IDL.Nat8), IDL.Text, IDL.Vec(IDL.Nat8)],
        [IDL.Text],
        [],
      ),
    'toggleFollowUpAppointment' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'unlockAdmin' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Bool], []),
    'updateAppointment' : IDL.Func([IDL.Nat, Appointment], [IDL.Text], []),
    'updateAttendance' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateLead' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Int,
          IDL.Nat8,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'updatePatient' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'updateStaffPermissions' : IDL.Func(
        [IDL.Text, StaffPermissions],
        [IDL.Text],
        [],
      ),
    'verifyAdminPassword' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };