/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminConfig {
  'hashedSecurityAnswer' : [] | [Uint8Array],
  'securityQuestion' : string,
  'hashedPassword' : [] | [Uint8Array],
}
export interface Appointment {
  'id' : bigint,
  'appointmentTime' : bigint,
  'notes' : string,
  'patientName' : string,
  'mobile' : string,
  'isFollowUp' : boolean,
}
export interface Attendance {
  'name' : string,
  'role' : string,
  'timestamp' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Lead {
  'doctorRemark' : string,
  'leadName' : string,
  'addToAppointment' : boolean,
  'area' : string,
  'treatmentWanted' : string,
  'leadStatus' : string,
  'rating' : number,
  'mobile' : string,
  'expectedTreatmentDate' : bigint,
  'followUpDate' : bigint,
}
export interface PatientView {
  'area' : string,
  'name' : string,
  'notes' : string,
  'prescriptionHistory' : Array<Prescription>,
  'image' : [] | [ExternalBlob],
  'mobile' : string,
}
export interface Prescription {
  'doctorNotes' : string,
  'prescriptionData' : { 'typed' : string } |
    { 'freehand' : ExternalBlob } |
    { 'camera' : ExternalBlob },
  'followUp' : [] | [string],
  'prescriptionType' : { 'typed' : null } |
    { 'freehand' : null } |
    { 'camera' : null },
  'medicalHistory' : [] | [string],
  'timestamp' : bigint,
  'patientName' : string,
  'symptoms' : [] | [string],
  'mobile' : string,
  'clinicName' : string,
  'allergies' : [] | [string],
  'appointmentId' : [] | [bigint],
  'consultationType' : { 'telemedicine' : null } |
    { 'inPerson' : null },
}
export interface Staff { 'name' : string, 'role' : string }
export interface StaffPermissions {
  'hasFullControl' : boolean,
  'canAccessSettings' : boolean,
  'canAccessAppointments' : boolean,
  'canAccessPatients' : boolean,
  'canAccessLeads' : boolean,
}
export type Time = bigint;
export interface UserProfile { 'username' : string, 'clinicName' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAppointment' : ActorMethod<[string, string, bigint, string], string>,
  'addLead' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      number,
      string,
      boolean,
      string,
    ],
    string
  >,
  'addPatient' : ActorMethod<
    [[] | [ExternalBlob], string, string, string, string],
    string
  >,
  'addStaff' : ActorMethod<[string, string, StaffPermissions], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAttendance' : ActorMethod<[string, string], boolean>,
  'deleteAppointment' : ActorMethod<[bigint], string>,
  'deleteLead' : ActorMethod<[string], string>,
  'deletePatient' : ActorMethod<[string], string>,
  'deletePrescription' : ActorMethod<[string, bigint], string>,
  'deleteStaff' : ActorMethod<[string], string>,
  'getAdminConfig' : ActorMethod<[], [] | [AdminConfig]>,
  'getAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAttendance' : ActorMethod<[], Array<Attendance>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getPatients' : ActorMethod<[], Array<PatientView>>,
  'getPrescriptionById' : ActorMethod<[string, bigint], [] | [Prescription]>,
  'getPrescriptions' : ActorMethod<[string], Array<Prescription>>,
  'getPrescriptionsLastModified' : ActorMethod<[], [] | [Time]>,
  'getStaff' : ActorMethod<[], Array<Staff>>,
  'getStaffPermissions' : ActorMethod<[string], [] | [StaffPermissions]>,
  'getTodaysAppointmentsSorted' : ActorMethod<[], Array<Appointment>>,
  'getTomorrowAppointmentsSorted' : ActorMethod<[], Array<Appointment>>,
  'getUpcomingAppointmentsSorted' : ActorMethod<[], Array<Appointment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[string, Uint8Array], string>,
  'register' : ActorMethod<[string, Uint8Array], string>,
  'resetAdminPassword' : ActorMethod<[Uint8Array, Uint8Array], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePrescription' : ActorMethod<[Prescription], string>,
  'setAdminPassword' : ActorMethod<[Uint8Array, string, Uint8Array], string>,
  'toggleFollowUpAppointment' : ActorMethod<[bigint], string>,
  'unlockAdmin' : ActorMethod<[Uint8Array], boolean>,
  'updateAppointment' : ActorMethod<[bigint, Appointment], string>,
  'updateAttendance' : ActorMethod<[string, string, string], boolean>,
  'updateLead' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      number,
      string,
      boolean,
      string,
    ],
    string
  >,
  'updatePatient' : ActorMethod<
    [string, [] | [ExternalBlob], string, string, string, string],
    string
  >,
  'updateStaffPermissions' : ActorMethod<[string, StaffPermissions], string>,
  'verifyAdminPassword' : ActorMethod<[Uint8Array], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];