/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Attendance {
    name: string;
    role: string;
    timestamp: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PatientView {
    area: string;
    name: string;
    notes: string;
    prescriptionHistory: Array<Prescription>;
    image?: ExternalBlob;
    mobile: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Lead {
    doctorRemark: string;
    leadName: string;
    addToAppointment: boolean;
    area: string;
    treatmentWanted: string;
    leadStatus: string;
    rating: number;
    mobile: string;
    expectedTreatmentDate: bigint;
    followUpDate: bigint;
}
export interface StaffPermissions {
    hasFullControl: boolean;
    canAccessSettings: boolean;
    canAccessAppointments: boolean;
    canAccessPatients: boolean;
    canAccessLeads: boolean;
}
export interface Staff {
    name: string;
    role: string;
}
export interface Appointment {
    id: bigint;
    appointmentTime: bigint;
    notes: string;
    patientName: string;
    mobile: string;
    isFollowUp: boolean;
}
export interface Prescription {
    doctorNotes: string;
    prescriptionData: {
        __kind__: "typed";
        typed: string;
    } | {
        __kind__: "freehand";
        freehand: ExternalBlob;
    } | {
        __kind__: "camera";
        camera: ExternalBlob;
    };
    followUp?: string;
    prescriptionType: Variant_typed_freehand_camera;
    medicalHistory?: string;
    timestamp: bigint;
    patientName: string;
    symptoms?: string;
    mobile: string;
    clinicName: string;
    allergies?: string;
    appointmentId?: bigint;
    consultationType: Variant_telemedicine_inPerson;
}
export interface AdminConfig {
    hashedSecurityAnswer?: Uint8Array;
    securityQuestion: string;
    hashedPassword?: Uint8Array;
}
export interface UserProfile {
    username: string;
    clinicName: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_telemedicine_inPerson {
    telemedicine = "telemedicine",
    inPerson = "inPerson"
}
export enum Variant_typed_freehand_camera {
    typed = "typed",
    freehand = "freehand",
    camera = "camera"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAppointment(patientName: string, mobile: string, appointmentTime: bigint, notes: string): Promise<string>;
    addLead(leadName: string, mobile: string, treatmentWanted: string, area: string, followUpDate: bigint, expectedTreatmentDate: bigint, rating: number, doctorRemark: string, addToAppointment: boolean, leadStatus: string): Promise<string>;
    addPatient(image: ExternalBlob | null, name: string, mobile: string, area: string, notes: string): Promise<string>;
    addStaff(name: string, role: string, permissions: StaffPermissions): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAttendance(name: string, role: string): Promise<boolean>;
    deleteAppointment(id: bigint): Promise<string>;
    deleteLead(mobile: string): Promise<string>;
    deletePatient(mobile: string): Promise<string>;
    deletePrescription(patientMobile: string, id: bigint): Promise<string>;
    deleteStaff(staffName: string): Promise<string>;
    getAdminConfig(): Promise<AdminConfig | null>;
    getAppointments(): Promise<Array<Appointment>>;
    getAttendance(): Promise<Array<Attendance>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLeads(): Promise<Array<Lead>>;
    getPatients(): Promise<Array<PatientView>>;
    getPrescriptionById(patientMobile: string, id: bigint): Promise<Prescription | null>;
    getPrescriptions(patientMobile: string): Promise<Array<Prescription>>;
    getPrescriptionsLastModified(): Promise<Time | null>;
    getStaff(): Promise<Array<Staff>>;
    getStaffPermissions(staffName: string): Promise<StaffPermissions | null>;
    getTodaysAppointmentsSorted(): Promise<Array<Appointment>>;
    getTomorrowAppointmentsSorted(): Promise<Array<Appointment>>;
    getUpcomingAppointmentsSorted(): Promise<Array<Appointment>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    login(username: string, hashedPassword: Uint8Array): Promise<string>;
    register(username: string, hashedPassword: Uint8Array): Promise<string>;
    resetAdminPassword(hashedSecurityAnswer: Uint8Array, newHashedPassword: Uint8Array): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    savePrescription(prescription: Prescription): Promise<string>;
    setAdminPassword(hashedPassword: Uint8Array, securityQuestion: string, hashedSecurityAnswer: Uint8Array): Promise<string>;
    toggleFollowUpAppointment(id: bigint): Promise<string>;
    unlockAdmin(hashedSecurityAnswer: Uint8Array): Promise<boolean>;
    updateAppointment(id: bigint, updatedAppointment: Appointment): Promise<string>;
    updateAttendance(_timestamp: string, name: string, role: string): Promise<boolean>;
    updateLead(mobile: string, leadName: string, newMobile: string, treatmentWanted: string, area: string, followUpDate: bigint, expectedTreatmentDate: bigint, rating: number, doctorRemark: string, addToAppointment: boolean, leadStatus: string): Promise<string>;
    updatePatient(mobile: string, image: ExternalBlob | null, name: string, newMobile: string, area: string, notes: string): Promise<string>;
    updateStaffPermissions(staffName: string, permissions: StaffPermissions): Promise<string>;
    verifyAdminPassword(hashedPassword: Uint8Array): Promise<boolean>;
}
import type { AdminConfig as _AdminConfig, ExternalBlob as _ExternalBlob, PatientView as _PatientView, Prescription as _Prescription, StaffPermissions as _StaffPermissions, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAppointment(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addAppointment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAppointment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addLead(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint, arg6: number, arg7: string, arg8: boolean, arg9: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addLead(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLead(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async addPatient(arg0: ExternalBlob | null, arg1: string, arg2: string, arg3: string, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addPatient(await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPatient(await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addStaff(arg0: string, arg1: string, arg2: StaffPermissions): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addStaff(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStaff(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAttendance(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.createAttendance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAttendance(arg0, arg1);
            return result;
        }
    }
    async deleteAppointment(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAppointment(arg0);
            return result;
        }
    }
    async deleteLead(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLead(arg0);
            return result;
        }
    }
    async deletePatient(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePatient(arg0);
            return result;
        }
    }
    async deletePrescription(arg0: string, arg1: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePrescription(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePrescription(arg0, arg1);
            return result;
        }
    }
    async deleteStaff(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStaff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStaff(arg0);
            return result;
        }
    }
    async getAdminConfig(): Promise<AdminConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminConfig();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminConfig();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointments();
            return result;
        }
    }
    async getAttendance(): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendance();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeads();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeads();
            return result;
        }
    }
    async getPatients(): Promise<Array<PatientView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatients();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatients();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrescriptionById(arg0: string, arg1: bigint): Promise<Prescription | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrescriptionById(arg0, arg1);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrescriptionById(arg0, arg1);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrescriptions(arg0: string): Promise<Array<Prescription>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrescriptions(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrescriptions(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrescriptionsLastModified(): Promise<Time | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrescriptionsLastModified();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrescriptionsLastModified();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStaff(): Promise<Array<Staff>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaff();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaff();
            return result;
        }
    }
    async getStaffPermissions(arg0: string): Promise<StaffPermissions | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaffPermissions(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaffPermissions(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodaysAppointmentsSorted(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodaysAppointmentsSorted();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodaysAppointmentsSorted();
            return result;
        }
    }
    async getTomorrowAppointmentsSorted(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTomorrowAppointmentsSorted();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTomorrowAppointmentsSorted();
            return result;
        }
    }
    async getUpcomingAppointmentsSorted(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingAppointmentsSorted();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingAppointmentsSorted();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async login(arg0: string, arg1: Uint8Array): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return result;
        }
    }
    async register(arg0: string, arg1: Uint8Array): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1);
            return result;
        }
    }
    async resetAdminPassword(arg0: Uint8Array, arg1: Uint8Array): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAdminPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAdminPassword(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async savePrescription(arg0: Prescription): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.savePrescription(await to_candid_Prescription_n34(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePrescription(await to_candid_Prescription_n34(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setAdminPassword(arg0: Uint8Array, arg1: string, arg2: Uint8Array): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminPassword(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminPassword(arg0, arg1, arg2);
            return result;
        }
    }
    async toggleFollowUpAppointment(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleFollowUpAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleFollowUpAppointment(arg0);
            return result;
        }
    }
    async unlockAdmin(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockAdmin(arg0);
            return result;
        }
    }
    async updateAppointment(arg0: bigint, arg1: Appointment): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointment(arg0, arg1);
            return result;
        }
    }
    async updateAttendance(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAttendance(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAttendance(arg0, arg1, arg2);
            return result;
        }
    }
    async updateLead(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: bigint, arg7: number, arg8: string, arg9: boolean, arg10: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLead(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLead(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            return result;
        }
    }
    async updatePatient(arg0: string, arg1: ExternalBlob | null, arg2: string, arg3: string, arg4: string, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatient(arg0, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatient(arg0, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateStaffPermissions(arg0: string, arg1: StaffPermissions): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStaffPermissions(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStaffPermissions(arg0, arg1);
            return result;
        }
    }
    async verifyAdminPassword(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdminPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdminPassword(arg0);
            return result;
        }
    }
}
function from_candid_AdminConfig_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminConfig): AdminConfig {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_PatientView_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PatientView): Promise<PatientView> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_Prescription_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Prescription): Promise<Prescription> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdminConfig]): AdminConfig | null {
    return value.length === 0 ? null : from_candid_AdminConfig_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Prescription]): Promise<Prescription | null> {
    return value.length === 0 ? null : await from_candid_Prescription_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StaffPermissions]): StaffPermissions | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hashedSecurityAnswer: [] | [Uint8Array];
    securityQuestion: string;
    hashedPassword: [] | [Uint8Array];
}): {
    hashedSecurityAnswer?: Uint8Array;
    securityQuestion: string;
    hashedPassword?: Uint8Array;
} {
    return {
        hashedSecurityAnswer: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.hashedSecurityAnswer)),
        securityQuestion: value.securityQuestion,
        hashedPassword: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.hashedPassword))
    };
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    area: string;
    name: string;
    notes: string;
    prescriptionHistory: Array<_Prescription>;
    image: [] | [_ExternalBlob];
    mobile: string;
}): Promise<{
    area: string;
    name: string;
    notes: string;
    prescriptionHistory: Array<Prescription>;
    image?: ExternalBlob;
    mobile: string;
}> {
    return {
        area: value.area,
        name: value.name,
        notes: value.notes,
        prescriptionHistory: await from_candid_vec_n22(_uploadFile, _downloadFile, value.prescriptionHistory),
        image: record_opt_to_undefined(await from_candid_opt_n30(_uploadFile, _downloadFile, value.image)),
        mobile: value.mobile
    };
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    doctorNotes: string;
    prescriptionData: {
        typed: string;
    } | {
        freehand: _ExternalBlob;
    } | {
        camera: _ExternalBlob;
    };
    followUp: [] | [string];
    prescriptionType: {
        typed: null;
    } | {
        freehand: null;
    } | {
        camera: null;
    };
    medicalHistory: [] | [string];
    timestamp: bigint;
    patientName: string;
    symptoms: [] | [string];
    mobile: string;
    clinicName: string;
    allergies: [] | [string];
    appointmentId: [] | [bigint];
    consultationType: {
        telemedicine: null;
    } | {
        inPerson: null;
    };
}): Promise<{
    doctorNotes: string;
    prescriptionData: {
        __kind__: "typed";
        typed: string;
    } | {
        __kind__: "freehand";
        freehand: ExternalBlob;
    } | {
        __kind__: "camera";
        camera: ExternalBlob;
    };
    followUp?: string;
    prescriptionType: Variant_typed_freehand_camera;
    medicalHistory?: string;
    timestamp: bigint;
    patientName: string;
    symptoms?: string;
    mobile: string;
    clinicName: string;
    allergies?: string;
    appointmentId?: bigint;
    consultationType: Variant_telemedicine_inPerson;
}> {
    return {
        doctorNotes: value.doctorNotes,
        prescriptionData: await from_candid_variant_n25(_uploadFile, _downloadFile, value.prescriptionData),
        followUp: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.followUp)),
        prescriptionType: from_candid_variant_n28(_uploadFile, _downloadFile, value.prescriptionType),
        medicalHistory: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.medicalHistory)),
        timestamp: value.timestamp,
        patientName: value.patientName,
        symptoms: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.symptoms)),
        mobile: value.mobile,
        clinicName: value.clinicName,
        allergies: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.allergies)),
        appointmentId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.appointmentId)),
        consultationType: from_candid_variant_n29(_uploadFile, _downloadFile, value.consultationType)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    typed: string;
} | {
    freehand: _ExternalBlob;
} | {
    camera: _ExternalBlob;
}): Promise<{
    __kind__: "typed";
    typed: string;
} | {
    __kind__: "freehand";
    freehand: ExternalBlob;
} | {
    __kind__: "camera";
    camera: ExternalBlob;
}> {
    return "typed" in value ? {
        __kind__: "typed",
        typed: value.typed
    } : "freehand" in value ? {
        __kind__: "freehand",
        freehand: await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, value.freehand)
    } : "camera" in value ? {
        __kind__: "camera",
        camera: await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, value.camera)
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    typed: null;
} | {
    freehand: null;
} | {
    camera: null;
}): Variant_typed_freehand_camera {
    return "typed" in value ? Variant_typed_freehand_camera.typed : "freehand" in value ? Variant_typed_freehand_camera.freehand : "camera" in value ? Variant_typed_freehand_camera.camera : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    telemedicine: null;
} | {
    inPerson: null;
}): Variant_telemedicine_inPerson {
    return "telemedicine" in value ? Variant_telemedicine_inPerson.telemedicine : "inPerson" in value ? Variant_telemedicine_inPerson.inPerson : value;
}
async function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PatientView>): Promise<Array<PatientView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PatientView_n20(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Prescription>): Promise<Array<Prescription>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Prescription_n23(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_Prescription_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Prescription): Promise<_Prescription> {
    return await to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    doctorNotes: string;
    prescriptionData: {
        __kind__: "typed";
        typed: string;
    } | {
        __kind__: "freehand";
        freehand: ExternalBlob;
    } | {
        __kind__: "camera";
        camera: ExternalBlob;
    };
    followUp?: string;
    prescriptionType: Variant_typed_freehand_camera;
    medicalHistory?: string;
    timestamp: bigint;
    patientName: string;
    symptoms?: string;
    mobile: string;
    clinicName: string;
    allergies?: string;
    appointmentId?: bigint;
    consultationType: Variant_telemedicine_inPerson;
}): Promise<{
    doctorNotes: string;
    prescriptionData: {
        typed: string;
    } | {
        freehand: _ExternalBlob;
    } | {
        camera: _ExternalBlob;
    };
    followUp: [] | [string];
    prescriptionType: {
        typed: null;
    } | {
        freehand: null;
    } | {
        camera: null;
    };
    medicalHistory: [] | [string];
    timestamp: bigint;
    patientName: string;
    symptoms: [] | [string];
    mobile: string;
    clinicName: string;
    allergies: [] | [string];
    appointmentId: [] | [bigint];
    consultationType: {
        telemedicine: null;
    } | {
        inPerson: null;
    };
}> {
    return {
        doctorNotes: value.doctorNotes,
        prescriptionData: await to_candid_variant_n36(_uploadFile, _downloadFile, value.prescriptionData),
        followUp: value.followUp ? candid_some(value.followUp) : candid_none(),
        prescriptionType: to_candid_variant_n37(_uploadFile, _downloadFile, value.prescriptionType),
        medicalHistory: value.medicalHistory ? candid_some(value.medicalHistory) : candid_none(),
        timestamp: value.timestamp,
        patientName: value.patientName,
        symptoms: value.symptoms ? candid_some(value.symptoms) : candid_none(),
        mobile: value.mobile,
        clinicName: value.clinicName,
        allergies: value.allergies ? candid_some(value.allergies) : candid_none(),
        appointmentId: value.appointmentId ? candid_some(value.appointmentId) : candid_none(),
        consultationType: to_candid_variant_n38(_uploadFile, _downloadFile, value.consultationType)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "typed";
    typed: string;
} | {
    __kind__: "freehand";
    freehand: ExternalBlob;
} | {
    __kind__: "camera";
    camera: ExternalBlob;
}): Promise<{
    typed: string;
} | {
    freehand: _ExternalBlob;
} | {
    camera: _ExternalBlob;
}> {
    return value.__kind__ === "typed" ? {
        typed: value.typed
    } : value.__kind__ === "freehand" ? {
        freehand: await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, value.freehand)
    } : value.__kind__ === "camera" ? {
        camera: await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, value.camera)
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_typed_freehand_camera): {
    typed: null;
} | {
    freehand: null;
} | {
    camera: null;
} {
    return value == Variant_typed_freehand_camera.typed ? {
        typed: null
    } : value == Variant_typed_freehand_camera.freehand ? {
        freehand: null
    } : value == Variant_typed_freehand_camera.camera ? {
        camera: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_telemedicine_inPerson): {
    telemedicine: null;
} | {
    inPerson: null;
} {
    return value == Variant_telemedicine_inPerson.telemedicine ? {
        telemedicine: null
    } : value == Variant_telemedicine_inPerson.inPerson ? {
        inPerson: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
